"""initial backend schema"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial_backend"
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.create_table("users", sa.Column("email", sa.String(255), nullable=False), sa.Column("username", sa.String(255), nullable=False), sa.Column("hashed_password", sa.String(255), nullable=False), sa.Column("full_name", sa.String(255)), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("is_verified", sa.Boolean(), nullable=False), sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("id", sa.String(36), primary_key=True))
    op.create_index("ix_users_email", "users", ["email"], unique=True); op.create_index("ix_users_username", "users", ["username"], unique=True)
    op.create_table("lessons", sa.Column("slug", sa.String(255), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("description", sa.Text()), sa.Column("content", sa.Text(), nullable=False), sa.Column("difficulty", sa.Integer(), nullable=False), sa.Column("domain", sa.String(255), nullable=False), sa.Column("module", sa.String(255), nullable=False), sa.Column("order", sa.Integer(), nullable=False), sa.Column("is_published", sa.Boolean(), nullable=False), sa.Column("prerequisites", sa.Text()), sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("id", sa.String(36), primary_key=True))
    op.create_index("ix_lessons_slug", "lessons", ["slug"], unique=True); op.create_index("ix_lessons_domain", "lessons", ["domain"]); op.create_index("ix_lessons_module", "lessons", ["module"])
    op.create_table("circuits", sa.Column("owner_id", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("description", sa.Text()), sa.Column("ir_json", sa.Text(), nullable=False), sa.Column("num_qubits", sa.Integer(), nullable=False), sa.Column("is_public", sa.Boolean(), nullable=False), sa.Column("related_lesson_id", sa.String(36), sa.ForeignKey("lessons.id")), sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("id", sa.String(36), primary_key=True))
    op.create_index("ix_circuits_owner_id", "circuits", ["owner_id"])
    op.create_table("circuit_versions", sa.Column("circuit_id", sa.String(36), sa.ForeignKey("circuits.id"), nullable=False), sa.Column("version_number", sa.Integer(), nullable=False), sa.Column("ir_json", sa.Text(), nullable=False), sa.Column("change_summary", sa.Text()), sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("id", sa.String(36), primary_key=True))
    op.create_index("ix_circuit_versions_circuit_id", "circuit_versions", ["circuit_id"])
    op.create_table("progress", sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("lesson_id", sa.String(36), sa.ForeignKey("lessons.id"), nullable=False), sa.Column("is_completed", sa.Boolean(), nullable=False), sa.Column("is_started", sa.Boolean(), nullable=False), sa.Column("mastery_level", sa.Float(), nullable=False), sa.Column("attempts", sa.Integer(), nullable=False), sa.Column("time_spent_seconds", sa.Integer(), nullable=False), sa.Column("last_attempted_at", sa.String(255)), sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("id", sa.String(36), primary_key=True))
    op.create_index("ix_progress_user_id", "progress", ["user_id"]); op.create_index("ix_progress_lesson_id", "progress", ["lesson_id"])
    op.create_table("conversations", sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("title", sa.String(255)), sa.Column("context_lesson_id", sa.String(36), sa.ForeignKey("lessons.id")), sa.Column("context_circuit_id", sa.String(36), sa.ForeignKey("circuits.id")), sa.Column("message_count", sa.Integer(), nullable=False), sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("id", sa.String(36), primary_key=True))
    op.create_index("ix_conversations_user_id", "conversations", ["user_id"])
    op.create_table("messages", sa.Column("conversation_id", sa.String(36), sa.ForeignKey("conversations.id"), nullable=False), sa.Column("role", sa.String(50), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("metadata", sa.Text()), sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("id", sa.String(36), primary_key=True))
    op.create_index("ix_messages_conversation_id", "messages", ["conversation_id"])
    op.create_table("simulation_runs", sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("circuit_id", sa.String(36), sa.ForeignKey("circuits.id"), nullable=False), sa.Column("backend", sa.String(255), nullable=False), sa.Column("mode", sa.String(50), nullable=False), sa.Column("shots", sa.Integer(), nullable=False), sa.Column("seed", sa.Integer()), sa.Column("status", sa.String(50), nullable=False), sa.Column("result_json", sa.Text()), sa.Column("error_message", sa.Text()), sa.Column("duration_ms", sa.Integer(), nullable=False), sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("id", sa.String(36), primary_key=True))
    op.create_index("ix_simulation_runs_user_id", "simulation_runs", ["user_id"]); op.create_index("ix_simulation_runs_circuit_id", "simulation_runs", ["circuit_id"])

def downgrade() -> None:
    for table in ["simulation_runs","messages","conversations","progress","circuit_versions","circuits","lessons","users"]: op.drop_table(table)
